# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-handbook-of-generative-ai
title: 量潮生成式人工智能手册
author: 量潮科技
description: 量潮及其合作伙伴总结生成式人工智能领域实践心得的工作手册
# Jupyter Book Config
only_build_toc_files: true